### PR TITLE
Spport new yome, "筒隠月子"

### PR DESCRIPTION
**Pull request by papix**
@gomayumax implemented new yome, "筒隠月子".
This pull request support this yome for dark bot, like "小路綾" and "小野寺小咲".

I think, this function is very exciting for us.
Please merge it!!!!!!!!!!!!!!!!!!!!!!!!

See also: http://dic.nicovideo.jp/a/%E7%AD%92%E9%9A%A0%E6%9C%88%E5%AD%90

### CODE REVIEW

**Comment by ara-ta3** [comment]
very cool!

**Comment by papix** [comment]
日本語でOK

**Comment by ara-ta3** [comment]
最高！！！！！！！！！！
デプロイed

**Comment by papix** [comment]
(∩´∀｀)∩ﾜｰｲ

**Pull request merged**
